name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: jurplel/install-qt-action@v1
    - uses: actions/checkout@v1
    - name: qmake
      run: qmake 
    - name: make
      run: make
    - name: make check
      run: make check TESTARGS="--platform offscreen"
